apiVersion: v1
kind: Service
metadata:
  name: admin-api
  namespace: tacokumo
spec:
  type: LoadBalancer  # Change to ClusterIP if using Ingress
  ports:
  - port: 8444
    targetPort: 8444
    protocol: TCP
    name: https
  selector:
    app: admin-api
