apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tacokumo

resources:
  - configmap.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - admin-api-deployment.yaml
  - admin-api-service.yaml
